### PR TITLE
fix warning about file type when uploading

### PR DESCRIPTION
**Pull request by ghost**
random warning is shown by Mastodon.py when uploading graph.png to mastodon servers

### CODE REVIEW

**Comment by clement-analogue** [comment]
I propose to revert this commit because it creates an error on some system, e.g. Ubuntu 16.04, cf #8

**Comment by ghost** [comment]
@clement-analogue can you elaborate please ? (can you past the error ?)
According to the documentation of Mastodon.py, if the mime is not provided to media_post function then a detection based will be performed. [media_post] (https://github.com/halcy/Mastodon.py/blob/master/mastodon/Mastodon.py#L688). So the change should not be the root case of the issue you are facing.

**Comment by clement-analogue** [comment]
If the mime type is defined manually as it is with this commit
`media_dict = mastodon.media_post(file_to_upload,"image/png")`
Then, I get the following error
```
{u'error': u'Validation failed: File content type is invalid, File is invalid'}
Uploaded file, returned:
{u'error': u'Validation failed: File content type is invalid, File is invalid'}
Tooting...
4 accounts 
+1 in the last hour

Traceback (most recent call last):
  File "usercount.py", line 199, in <module>
    mastodon.status_post(toot_text, in_reply_to_id=None, media_ids=[media_dict] )
  File "/usr/local/lib/python2.7/dist-packages/mastodon/Mastodon.py", line 517, in status_post
    raise MastodonIllegalArgumentError("Invalid media dict: %s" % e)
mastodon.Mastodon.MastodonIllegalArgumentError: Invalid media dict: 'id'
```
To make it works, I just reverted the change
`media_dict = mastodon.media_post(file_to_upload)`
My system is Ubuntu Xenial 16.04 with python 2.7.12

**Comment by ghost** [comment]
Interesting seems that the upload is failling because mastodon is refusing the mime provided in your case. I suppose you didn't change the picture file type ? anyhow can you run a test without this commit and  with a small edit to display the mime guessed by Mastodon. (to check what could be the difference)

replace line 702 of /usr/local/lib/python2.7/dist-packages/mastodon/Mastodon.py
to:

```
mime_type = mimetypes.guess_type(media_file)[0]
print mime_type

```

**Comment by clement-analogue** [comment]
No, I didn't change the picture file type.

With the change, here the result of the guessed picture file type :
`image/png`

**Comment by ghost** [comment]
now I am confused :). its the same value as in this commit.

**Comment by ghost** [comment]
oh wait, I think I see the root cause. On top of guessing the mime the file to be uploaded is opened in rb mode. This means that you are right and this commit should reverted or adjusted to do something like : 

`media_dict = mastodon.media_post(open(file_to_upload,'rb'),"image/png")`
instead of

`media_dict = mastodon.media_post(file_to_upload,"image/png")`

**Comment by clement-analogue** [comment]
yes, so better keep it simple with
`media_dict = mastodon.media_post(file_to_upload)`

**Pull request merged**
